import { Injectable } from '@angular/core';
import { Tile } from './tile';
import { KeyedCollection } from 'KeyedCollection';
import { Description } from './description';


@Injectable({
  providedIn: 'root'
})
export class TileService {


  tiles = new KeyedCollection<Tile>();

  //Details Info properties
  tileTitle = new Array<string>();
  tileDescription = new Array<string>();

  constructor() {
    for (let i = 1; i <= 24; i++) {
      let imagePath = 'https://lapstg01.blob.core.windows.net/lap04/image%20(' + (i-1) + ').jpg';
      let newTile = new Tile(i, imagePath);
      this.tiles.Add(String(i), newTile);
    }

    this.tileDescription.push(""); // [0] is empty
    this.tileDescription.push(`<p text-indent='70px'>Welcome to the quilt. We’re glad you found us. This multimodal project spans a year of scholarship, sewing, and social justice. With it we try to represent our experience accurately: a physical/digital compilation of mixed media, mixed methods, mixed writers, theories, and identities. Our digital quilt represents our physical quilt, and our physical quilt represents our embodied realities. Our immediate goal is simple, to contribute to ongoing conversations about critical making as composition pedagogy and provide pedagogical and practical implications for employing critical making in the writing classroom. Our larger goal is to solidify the connections between critical making and decolonial rhetorics, advancing critical making as a decolonial classroom option that answers the pedagogical and curricular needs of historically underrepresented student populations (Austin & Oseguera, 2004). As you explore the quilt we invite you to consider these goals and use our journey as evidence of critical making as decolonial writing classroom praxis.</p>`);
    this.tileDescription.push(`<p>Who are we? We are quilters; but we started as an assistant professor of composition studies, two students in an upper division writing in the disciplines course, a student interested in decolonial theory and undergraduate research, and a computer science student interested in coding. In the process of becoming quilters we have each found ways to define our roles and identities in relationship to scholarship, writing, and critical making. Like the individual blocks of our physical quilt, we maintain our agency and autonomy in our separate goals and identities while still coming together to inform this project. Respectful of these quilting lessons and outcomes, this essay represents our individual voices and experiences. As this work will argue, part of reframing composition through maker projects, rasquachismo, and decolonial social justice projects is to broaden the scope of who counts and what counts as composer, expert, and authority. Thus, this article is a practice in that very work. The authors represent a “quilting together,” if you will, of voices, experiences, and expertise. True to quilting etiquette, the authors refuse the traditional genre of standard edited academic article and instead allow their individual writing to maintain its own style. The article itself, then, is also “quilted composition:” four voices, ideas, and experiences sewn together by transitions, section breaks, and collaborative effort, bound by the conventions of an academic article, and pieced together through coded webtext. Our shifts in voice, style, tone, and ideas are purposeful, even if at times awkward. We give credit to individual voices when necessary and come together as one when our ideas converge.
    </p><p>Our digital quilt explores “Quilting Composition” through research and reflection. Although we invite you to interact with the quilt in your own way, Kelly introduces the project, and then Leslie provides the history of quilting and textile arts and their relationship to rhetoric and composition, emphasizing their usefulness as decolonial, feminist social justice projects. Next, Giana discusses textile arts and maker projects as composition classroom pedagogy, and the current trends in composition and critical making. Alyssa follows with a look at methodology; more specifically, how is it that quilting composition is both theory, method, and actual practice of an intersectional chicanx, decolonial, feminist approach to teaching and understanding writing. Finally, Erik codes our writing together into a digital quilt. Using the theoretical foundation of quilting as social justice maker project and classroom composition praxis, we provide observations from our experiences throughout, as students, instructors, and outside researchers. We conclude by arguing that quilting, when contextualized as decolonial, feminist, rasquache maker project is specifically useful for teaching students about writing, but also for encouraging them to see the risks and rewards of writing in its myriad forms as a tool for social justice and advocacy.
    </p>`);
    this.tileDescription.push(`<p>It was Semester’s Eve in spring of 2018 and I sat facing my computer nervously: Should I make the syllabus live now, or wait until we meet tomorrow? I’m guessing this is a familiar place for all instructors, but spring of 2018 was especially poignant for me because somewhere between October of 2017 and January of 2018 I threw caution to the wind to embark on a crazy composition classroom adventure: I decided we would be quilting. Like, really quilting. Fabric, needles, thread—the whole thing. I scoured the names of the 26 students who were about to become part of my project. Do any of these names sound like quilting names? Should I wait until they’re already trapped in the classroom on the first day to spring the quilt idea? I decided to be a benevolent quilt leader and publish. Within two hours three students had dropped. By the end of the day the roster had shifted significantly. Students dropped, panicked last minuters added, and a core of the strong (or those that didn’t bother to check) held fast. There was a low din when I entered the classroom the next day. It slowed as I started taking off my jacket and preparing. At exactly 3:00 pm I began to introduce myself and welcome everyone to the class. I hadn’t even broken into the syllabus when a hand shot up. “Yes?” I said, nervously, “I’m sorry,” said the student, “are we really going to make a quilt in this class? This is GWAR  right?” “Yes,” I paused longer than I should have, “this is GWAR. And we’re making a quilt.” Excited chatter as students turned to each other in disbelief. I laughed nervously and said, “hear me out…” By the end of the two-hour class meeting everyone – myself included! - was nervous, but on board. We were doing it! It was my second semester in a tenure track position and I had never quilted anything. Ever.
    </p><p>The idea for the quilting composition came to me during a maker session co-hosted by Sonia Arellano at the fall 2017 Feminisms and Rhetorics conference. Arellano presented her research, which looked at the Migrant Quilt Project,  an inspiring social justice group that uses found materials from the bodies of migrant desert crossers in southern Arizona to make quilts that raise awareness about the perils faced by migrants on the southern border (Arellano, Quilting the Migrant Trail, 2017). Her quilt, her research, and what the Migrant Quilt Project accomplished through critical quilt making amazed me. I’m a chicana who was born and raised in southern New Mexico about 45 minutes from the El Paso/Ciudad Juárez border. Immigration, transnationalism, and the borderlands are central to my identity, both scholarly and otherwise. But so is “making.” My dad, who raised me, is a construction worker who brought me up in a “we can either fix it or make it” household. I spent my summers and weekends framing out forms, pouring cement, hanging drywall, doing tile, and plastering. Sitting back after a day of hard labor under the hot New Mexico sun, my skin baked brown and my hands blistered or covered in plaster, drinking a coke while my dad sipped a beer and admiring our work is among my favorite memories. There is something so satisfying about making, and the satisfaction I feel after completing a cement patio or tiling a shower surround is the same satisfaction I feel after writing an article or engaging in other academic work. And quilting, although quite a leap from construction, presented me with a way to bridge these two epistemologies.
    </p>`);
    this.tileDescription.push(`<p>After Arellano’s presentation, I started researching other sewing for social justice and maker projects across rhetoric and composition. I found inspiration in the syllabi of Malea Powell (2014), Sonia Arellano,  and Jennifer Sano-Franchini (2019), and the theoretical work of Angela Haas (2012), Matt Ratto and Megan Boler (2014), Jodi Shipka (2011), and David Sheridan, Jim Ridolfo, and Anthony Michel (2012), who all encourage us to extend our definition of writing (and research) to include critical making. I also turned to my own experiences for inspiration. My dad’s “fix it or make it” mentality had left a large streak of rasquachismo in me that found its way into my academic work. We will continue to expand our definition of rasquachismo as we move through this piece, but the basic definition comes from Tomás Ybarra-Frausto (1989), who theorizes rasquachismo as “an underdog perspective - a view from los de abajo. An attitude rooted in resourcefulness and adaptability yet mindful of stance and style” (p. 5). He continues by arguing that rasquachismo is “visceral,” an “aesthetic display projecting a sort of visual biculturalism.” Rasquache is both embodied as a sensibility (visceral) and an “aesthetic,” something visible and visual. It is more than just a method for creating art, rasquache is a theory and analysis of how and why art is made. A rasquache methodology accounts for both the invisible and the visible by attaching sensibility and aesthetic to the work of researching, making methodology tangible both as a bodily practice and visible representation of how rhetoric and composition research proceeds. Sarah Lowndes (2016) connects DIY projects back to rasquache, although she doesn’t name it as such, stating, “DIY activities are often carried out using an economy of means and materials, and exhibit what could be called an aesthetic of necessity” (p. 263). I approached the quilt through rasquachismo, as I do most things.
    </p><p>As I continued my search on quilting, critical making, and social justice, I found projects doing similar work here in the US, like the Social Justice Sewing Academy,  The Migrant Quilt Project, and in Marsha MacDowell, et al.’s (2016) Quilts and Human Rights. I started thinking about the power of textile production as social action and cultural awareness in its myriad forms, but I also started thinking about Cooperative Argumentation (Makau & Marty, 2001): the theoretical underpinnings for my GWAR class that encourage students to engage in ethical dialogue and deliberation as a framework for sound and egalitarian decision making. Quilting seemed to do all of that. It presented a way for students to work both individually (on their own quilt block) and as a group (to bring the whole quilt together). The work they engage in would help them make tangible the labor of research, the production of rhetorical artifacts, and see themselves as dynamic pieces of larger systems of labor, production, and audience. I also felt that my students, many of who also come from backgrounds where physical labor is lived reality, might find the same value and satisfaction in making that I do.
    </p><p>So I hatched the plan of the quilt. As a class, we would spend all semester making a quilt.  The project would grow and change from an individual, to small group, to large group project. While we made the quilt, we’d talk about research, writing, rhetoric, social justice, and advocacy through the framework of cooperative argumentation. But, I had a really rasquache problem, and I imagined my students would too. Remember when I told you about all the things I grew up making? None of those were a quilt. My house was a construction house, not a sewing house. While he can maneuver a finishing trowel with finesse and precision, I can only imagine needles snapping against my dad’s thickly callused fingers while he tried to hem a pair of pants. I didn’t know how to sew, I didn’t own any fabric, sewing equipment, or supplies. I didn’t even own an iron! To be perfectly honest, when I set out I wasn’t even necessarily sure of the parts of the quilt. My original syllabus and assignments expose my naivety. I refer to quilt blocks as quilt squares and I call seams margins. But, I believe in transfer (Yancey, Robertson, & Taczak, 2014), and rasquache is really all about that, too. If I can remodel a bathroom I can surely sew together a quilt! It's not so different really, is it? The rest of this essay will explore that question, while touching on key theoretical frameworks and engaging with our individual experience as part of this project.
    </p>`);
    this.tileDescription.push(`<p>As the fields of rhetoric and composition continue to recognize critical making as being valuable to performing composition, scholars and teachers are seeking ways to include innovative pedagogies in their classrooms that will encourage students to reimagine composition by redirecting their attention to the merit in historically undermined epistemologies. As defined by Ratto and Ree (2012) critical making refers “to [the] use [of] material forms of engagement with technologies to supplement and extend critical reflection and, in doing so, to reconnect (…) lived experiences with technologies to social and conceptual critique.” Textiles “extend the critical reflection” of a student in the classroom and consequently allow students to connect bodies and lives through performance and production. Quilts, among other textiles, often receive praise for their aesthetics over other intrinsic values. People appreciate quilts for their practical and artistic worth, overlooking and undermining the rhetorical weight of these textiles. However, more recently, researchers have gained an interest in studying how textiles visually represent history. This, in turn, allows scholars to understand how culturally produced textiles act as technical documents and, thus, perform composition (MacDowell et al. 2016).
    </p><p>In the many histories of the world, textiles have had and continue to play a prominent role in the lives of underrepresented communities: wampum, huipiles, slave quilts and the AIDS Memorial Quilt are just a few common examples. American Indian communities “employed wampum belts as hypertextual technologies—as wampum belts have extended human memories and inherited knowledges through interconnected, nonlinear designs and associative storage and retrieval methods—long before the “discovery” of “Western hypertext” (Haas, 2007, p. 77). This positions American Indians as the “first known skilled multimedia workers and intellectuals in the Americas” (Haas, 2007, p. 78). To this community the “wampum is a living rhetoric that communicates relationship between two or more parties” as it has “serve[d] as a sign of technology that has been used to record hundreds of years of alliances within tribes, between tribes, and between the tribal governments and colonial government” (Haas, 2007, p. 78). Wampum belts function as a living rhetoric because “[they] extend human memories of inherited knowledge via interconnected, nonlinear designs with associative message storage and retrieval methods” (Haas, 2007, p. 80-81). Like Haas, some Native American scholars express frustration when western hypertext theorists are credited with “inventing“ the concept of hypertextuality. Western theorists typically and historically credit to Vannevar Bush, an American. To counter this inaccurate narrative, Native Americans must “offer a preliminary hypertextual historiographical decolonial narrative that suggests that the concept of hypertext and the rhetorical work it does are not new – nor is it unique to Western culture, despite the terminology’s Western etymology” (Haas, 2007, p. 82-83). In fact, wampum is an example of pre-Memex, pre-Xanadu, and pre-Internet American Indian technology. Aside from qualifying as a multimodal hypertext, the wampum contains digital, visual, and spoken rhetoric because of it connection with spoken word. The wampum embodies “a hybridization of the oral tradition and symbolism (…) woven into the material rhetoric” (Haas, 2007, p. 90). The recognition of the wampum belt as a multimodal hypertext is important as it:

    </p><p>Situates American Indians as techno-savvy, as it demonstrates how American Indians have a long-standing intellectual tradition of multimedia, digital rhetoric and theories and practices – or theories and practices of communicating via the encoding of information without fingers and toes using a variety of media (Haas, 2007, p. 94).

    </p><p>Like wampum, huipiles—a Guatemalan indigenous hand-embroidered textile and a traditional garment—“can reveal age, sex, status, or it can state degrees of group membership and participation in different systems of beliefs, concealing individual identities in military uniforms or religious robes” (Odland, 2006, p. 2). Since indigenous Guatemalan artists create huipiles with the purpose of being read, one can argue that the creators of these textiles write through multimodal textiles to share a message with the readers of the fabric, members the community who can decode the symbols present in the textile. Odland supports Haas’ research on wampum, further demonstrating that indigenous communities have extensive traditions of multimodality. Odland (2006) states that “because each community has developed its own style, form, pattern, and color that serve as symbols of identity and meaning, we can assume that the Maya have practiced their weaving traditions for a long time” (p. 2). The huipil remains a “cloth [with] unlimited potential for communication graphically and emblematically” (Odland, 2006, p. 2).
    </p><p>Similar to cultural histories sewn into wampum and huipiles, quilts became an important piece of the fight against slavery in the 19th century in the United States. Organizers of the Underground Railroad quilted slave codes into quilts to help the enslaved navigate their way to freedom. In Hidden in Plain View: A Secret Story of Quilts and the Underground Railroad, authors Jacqueline Tobin and Raymond G. Dobard (2000) share their findings from a discussion with Ozella McDaniel Williams, a quilt maker from South Carolina. During the interview Williams “told researchers that she memorized a secret code passed down by her ancestors that was used by the quilt makers before the Civil War to offer discreet clues to slaves who were trying to escape to freedom in the North” (p. 44).  Tobin and Dobard (2000) “believe that particular quilt squares which showed wrenches in a particular pattern or pointed in a particular direction were hung outside of slave housing to signal other slaves it was time to gather their tools and other belongings and try to escape” (p. 44). As demonstrated through wampum, huipiles, and slave quilts, textiles continue to express and/or resist the oppression of minority communities. Creating something that is not only a functional garment or tool but also embodies resistance requires those that make them to be aware of the composition of their pieces so they reflect their intended double purpose. Textiles’ historical lack of recognition as multimodal texts overlooks the contributions of underrepresented groups to the field of rhetoric and composition and quilting and other textile art serve as method for sharing and understanding a more accurate narrative about the history, lived experiences, and rhetorical practices of historically marginalized groups. Understanding the presence textiles have in the lives of underrepresented groups acts as a critical race counterstory (Martinez, 2016) to the traditional rhetorical histories and narratives and allows for a deeper understanding of the function of textiles as multimodal texts.
  </p>`);
    this.tileDescription.push(`<p>Situating quilts in the decolonial histories of cultural textile production, quilts, then, can be considered a multimodal text, but also a digital archive and a hypertext. If you take the definition of digital, which refers to our fingers, our digits, like Angela Haas (2007, p. 84) does, and you take the definition of archive, meaning the collection of data, texts, images, and so forth, like Cheryl Bolick (2006, p. 122) does, then we can argue that the quilt itself is a digital archive. Ellen Cushman (2003) discusses decolonizing a digital archive in her essay “Wampum, Sequoyan, and story.” She states, “digital archives have changed both the processes and sites of knowledge making for composition and rhetorical scholars” (2003, p. 116). Actual digital archives are digital places where knowledge is stored, but the quilt we produced in our classroom is also a digital archive because we made it with our hands and it is a place where our knowledge is kept. Outsiders of the class might not be able to get the full amount of information and knowledge stored in our multimodal text/digital archive, but the same could be said of other types of texts, like proper traditional ones like research essays, or other visual texts, like paintings. Other texts might be too difficult to understand without outside context or knowledge, just like our quilt. However, unlike written texts, our quilt makes the information more accessible. Visual literacies, which is another name for visual texts, don’t always have to be in English (Glenn & Enoch, 2010), or they might not have any writing at all.
    </p><p>Like digital archives, hypertexts are a way to store information. When thinking of hypertexts, you probably think of the internet, however, it’s much more than that. Farkas and Farkas explains, “Hypertext theory considers how various arrangements of nodes and links express meaning and how these arrangements are reflected in the user interface. Hypertext theory classifies these arrangements of nodes and links into various kinds of hierarchical and non-hierarchical structures, often called ‘information structures’” (2002, p. 123)[4]. Edward Ayers explains hypertexts as having the ability to “create capacious spaces in which users make connections and discoveries for themselves” (2001, p. 6)[5]. The nodes and links on our quilt were the blocks, each of them connecting to another piece. Based on where each block lies gave it a different meaning over. Making these connections leads to discoveries about identity, agency, and “passionate attachments” (Butler, 1997, p. 7).  During the quilting process, we made a lot of discoveries about ourselves, ranging from whether we can thread a needle to what drove our individual commitments to equity, activism, and allyship.
    </p>`);
    this.tileDescription.push(`<p>Building on the history of textiles as record keepers, hypertexts, and social justice projects, contemporary quilting projects shed light on the rhetorical power of quilts and quilting as community-based social action compositions. As discussed in a previous section, Arellano’s research on the Migrant Quilt Project uncovers the rhetorical functions present in memorializing quilts. The quilts in the Migrant Quilt Project, including Arellano’s quilt, are crafted from clothing left behind by migrants crossing the desert. Arellano examines this cultural production as a meaning-making practice that memorializes lives of migrants and uncovers it through counter narrative (Mora, 2014). Activist quilts humanize and memorializes migrant lives and raise awareness of the reality of human migration. In Arellano’s (2017) dissertation, she theorizes quilting as a method to argue that meaning-making provides rhetoric and composition scholars with many pedagogical tools to encourage undermined ways of knowing. Similarly, Blair and Michel’s the NAMES Project AIDS Memorial Quilt memorializes the deaths of hundreds of thousands of victims of AIDS. The quilt “executes, in other words, multiple rhetorical deaths and give rise a great many others. All those are important in evaluating the legacy of this unusual commemorative monument” (Blair & Michel, 2007, p. 595-96).
    </p><p>Like the Migrant Quilt Project, the AIDS Memorial Quilt uses different materials to create a panel significant to or representative of the lives of the victims. Thus, as these contemporary social justice quilting projects show, it is not only important to consider the aesthetic value of the finished quilts but also to consider the materials and techniques quilters use to create their pieces. This is especially significant when considering the quilting processes of communities of color. For example, scholar and theorist bell hooks (1990) notes a distinct connection between representation, rhetoric and composition, and the art of quilt making. hooks argues that for black women, quilting was a “meditative process” requiring a special feminist critical commentary. The underprivileged economic and social circumstances experienced by black quilters “demanded exercising creative imagination in ways radically different from those of white female counterparts, especially women of privilege who had greater access to material and time” (bell hooks, 1990, p. 118). hooks continues by showing how the use of “leftovers” or pieces “of no value” became a valuable, meaning-making rhetorical practice in its own right, an active “counter story” to who counts and what counts as traditional quilt/quilting/quilter. Similar to hooks’ observation about black quilters, the quilt and quilting practices used by Kelly and her students were a deliberate act of rasquachismo: a chicanx art form and aesthetic.
    </p>`);
    this.tileDescription.push(`<p>Rasquachismo is a redefined term whose definition was reversed by the Mexican and Chicanx art movement. “Both in Mexico and the United States rasquachismo retains connotations of vulgarity and bad taste, a sense of being cursi” (Ybarra-Frausto, 1989, p. 5). However, “to be rasquache is to be down but not out fregado pero no jodido” (Ybarra-Frausto, 1989, p. 5). Rasquachismo “provoke[s] the accepted “superior: norms of the Anglo-American with the everyday reality of Chicano cultural practices” (Mesa-Bains, 1999, p. 158). This is because “operating as an internally colonized community within the borders of the United States, Chicanos forged a new cultural vocabulary composed of sustaining elements of Mexican tradition and lived encounter in a hostile environment” (Mesa-Bains, 1999, p. 159). Kelly used rasquachismo to inform the pedagogy of the quilt project. Instead of committing countless dollars to materials, Kelly encouraged her students to “make do” with any and all available resources. Rasquache quilting elevates both the intrinsic and extrinsic value of the quilt. While the individual designs symbolizes each student’s “passionate attachment,” the materials they incorporated into their block also represent their lived realities. Across the different blocks there are marked differences in fabrics and decorative materials. It is easy to spot which students had the resources to purchase new fabrics and materials, which used found materials, and which did a mix of the two. Each of these different approaches says something about the student who created the block and adds a robust aesthetic quality to the quilt. </p>`);
    this.tileDescription.push(`<p>In addition to rasquachismo, the quilt is also an act of apparent feminism. According to Erin Frost, “apparent feminism is a methodology that seeks to recognize and make apparent the urgent and sometimes hidden exigencies for feminist critique of contemporary rhetorics” (2015, p. 5). What this means is that apparent feminism brings a feminist critique to certain things you wouldn’t usually think as doing feminist work. The interesting thing about apparent feminism is that anyone can be an apparent feminist without identifying directly as just a feminist. The methodology “invites participation from allies who do not explicitly identify as feminist but do work that complements feminist goals” (Frost, 2015, p. 5). When we began to quilt we all didn’t have feminism directly in mind, but since popular stereotypes about quilting assume it is a “woman craft,” then everyone who took part in the quilt could consider themselves apparent feminists. One of the first questions audiences ask us when presenting our project is how straight cisgender male students engaged in the project. Without tackling why the problem with this question is often the question itself (what makes the person asking assume they might react differently than any other student, and, ultimately, why should it matter how they react?) recasting critical quilt making as apparent feminism subverts the need to argue explicitly one way or the other, engaging students in active feminisms through critical making. By challenging historic assumptions about who quilts and why, students are engaged in apparent feminist practices as allies, accomplices, and activists.</p>`);
    this.tileDescription.push(`<p>As we have explored throughout this digital quilt, our physical quilt is a multimodal text. Multimodality is a “theory [that] offers a broadly semiotic approach to analyzing most communicative forms, including spoken and written language, still and moving images, sound, music, gesture, body posture, movement and the use of space, and so on” (Bazalgette & Buckingham, 2012, p. 1). Multimodality encourages students to analyze information differently than traditional print texts do, since students not only have to analyze the words but also the images.
    </p><p>When asked to use multimodal texts in classrooms, teachers are often confused because they don’t know what multimodality includes, and just assume that it has something to do with having fun and not learning (Bazalgette & Buckingham, 2012, p. 4). Both of these reasons are justified, because multimodal texts do include television shows, movies, and even video games. However, what most teachers and professors don’t know is that it could also be as simple as having a conversation with another person. Gunther Kress explains how communication can be multimodal by stating: “Communication here is multimodal: by speech at times, by gaze, through actions… Communication had happened when one of the participants has focused on some aspect of the interaction” (2012, p. 6). Kress is arguing that communication is multimodal itself because of the various information that a person must take in at one time while communicating with someone else. Whether it’s a video game, a little chat, or sewing a quilt, when used thoughtfully and purposefully, multimodality can lead to critical making and mean making.
    </p>`);
    this.tileDescription.push(`<p>Critical making is “positioned at the intersection of ‘scholarly’ work of thinking and the material work of making; it serves as a catalyst for design, embedded in a process of craft, material, and exploration” (Schwartz, 2016, p. 227). This means critical making is a way for scholars to make their work tangible and physical, making the products and processes of that work visible to larger audiences. Basically, it’s like we’re building our critical scholarly work into existence. Critical making is also “a pedagogical construct in which students explore abstract concepts through the creation of physical things” (Schwartz, 2016, p. 229). Because critical making makes the abstract parts of critical thinking more visible, it helps students learn better. An important proponent of critical making is mean-making.
    </p><p>Mean making is, according to Barbara Bird (2010), “a construction through interpretive interactions with reading and writing” (p. 1). Paul Duncum (2004) agrees, but also claims that mean making isn’t just made through reading and writing, but also through “an interaction of music, the spoken word, sound effects, language, and pictures” (p. 252). Mean making is making something after having interactions with texts, whether they be the tradition text kind or the multimodal kind. During Dr. Medina-López’s class, we read and discussed articles. We learned through both multimodal texts and what Bazalgette and Buckingham (2012) call “proper” texts, meaning printed and/or written texts (p. 4). These texts helped us to create the quilt. The quilt was the product of our mean-making, and in turn, the quilt can help us mean-make in more robust and dynamic ways, since the quilt itself is multimodal. Jing Liu (2013) argues that visual texts, which are multimodal texts, can help with mean-making by stating, “We live in an increasingly visual culture, image colors and other non-verbal resources are no longer used mainly to entertain and illustrate, rather, they are being significant in communicating and meaning-making” (p. 1259). Multimodal texts are the way of the future, but that doesn’t mean classrooms have to completely give up on proper texts. Rather, they can integrate multimodal texts with these proper texts. Students can learn from both, without taking the significance and the importance of the other.
    </p>`);
    this.tileDescription.push(`<p>Understanding contemporary theory in maker projects and technical communication supports the claim that the collaborative process of quilting allows students to recognize quilts as technical documents and, therefore, realize the value they bring to composition. In Toward a Composition Made Whole, Shipka (2011) describes an experience she had while facilitating a workshop. The workshop’s focus was to provide support for teachers wanting to implement pedagogies “catered to students who favored creative, hands-on approaches to instruction and were open to diverse kinds of learnings” (p. 1). In her own classes, she “focus[ed] on tasks that invited students to experiment with alternative, hybrid, or diverse tasks of discourse” (Shipka, 2011, p. 1).  She was not too familiar with the attendee’s experiences in relation to multimodal composing so as a sample she selected a pair of pink ballet shoes. The pink ballet shoes had a transcribed research-based essay on them. Immediately after showing the sample, a teaching assistant from the history department began to ask questions like: “How is that college-level academic writing?” or “How can that possibly be rigorous?” (Shipka, 2011, p. 3). To Shipka (2011), the importance lies in “work[ing] closely with the student over the month she spent working on the shoes—in ways that allowed [her] to see, and so to understand, the final product in relation to the complex and highly rigorous decision-making the student employed while producing [the] text” (p. 3). The questions asked by the individual are pieces of evidence to support the claim of an existing “privileging of a linear, academic essayist prose style” and one “that pre-dates the recent proliferation of electronic communicative devices” (Samuels, 2007, p. 105). The traditional style Samuels points to discourages students from valuing their historically undermined epistemologies. The focus shifts in relation from the final product to the decision-making process. Implementing a multimodal approach in composition classrooms will not make a composition course less credible or less intellectually challenged for a student because the multimodal projects act as a metaphor for teach students about the writing process.  </p>`);
    this.tileDescription.push(`<p>Composition pedagogy is slow to progress in how it caters to the modern technological needs of students and. García-Galera and Valdivia (2014) acknowledges that in recent decades English classrooms embraced media as a text for students to analyze, but modern materials shifted teachers and students from the position of a consumer to a prosumer of new media. Pedagogical practice stalled the implementation of multimodal texts in classroom production. Providing access to multi-modalities in composition classes would benefit both students and teachers, offering students the option to communicate and express their knowledge and learning abilities in multiple ways (Diaz & McKenna, 2017). The stalling of multimodality into the studies of composition forms a barrier around students who continue to struggle with more traditional composition pedagogy. Bringing forth the integration of creative works in composition studies would open up learning to those who struggle with one-dimension or single-intelligence based teaching practices (Diaz & McKenna, 2017).
    </p><p>In higher education, composition has a documented history as a gatekeeping mechanism (Shaughnessy 1976; Bartholomae 1985; Rose 2009), especially for underrepresented minority students. For students, it does not matter what their selected major is, completing a requisite composition course is mandatory to prove that one has the capability of handling college-level reading and writing. The National Council of Teachers of Education Position Statement on Multimodal Literacies (2005) states, “in personal, civic, and professional discourse, alphabetic, visual, and aural works are not luxuries, but essential ways of knowing.” Yet, contemporary composition pedagogy does not take into consideration students who come from a variety of marginalized and non-traditional backgrounds, and learn in different ways. For the upper division composition writing college course at California State University, Monterey Bay, that change came through the critical quilt making project.
    </p><p>Institutions can become more supportive of teachers who follow composition pedagogies that let students engage more fully with their work, letting them become more connected to what they are writing and creating. Traditionally, writing is a “physical manifestation of communication” and “denotes a specific product to produce” (Newman, p. 2). Writing came to prevalence because the materials that have, historically, been widely available for composition: pen and paper (Newman, p. 2).  Writing remains the most widely used form of self-expression there is, yet the boundaries of writing are still very narrow. Expanding our definition of writing beyond the basics give us more tools and more options for expressing ourselves in powerful communicative forms.
    </p>`);
    this.tileDescription.push(`<p>As composition scholars and practitioners continue to recognize that they need to change the historic understanding of composition, they should seek ways that challenge the current traditions of composition pedagogy. James Berlin argues that our social environment affects how one understands and engages with discourse and language (Ruiz & Sanchez, 2016). Students of color face a challenge within composition studies as students of color might engage different dialects than what we traditionally consider “proper” or “correct.” For example, historical classifications of African American Vernacular English (AAVE), which was once referred to as Ebonics, marks it as an illegitimate form of communication because of the shortening of letters in words. Alphabetic language is a hallmark of the civilized and an advancement of people (Ruiz & Sanchez, 2016, p. 8). In the higher education system, which is built on white, western culture, AAVE does not fit into traditional definitions of “civilized” language. The differences in communication styles of people of color are widely criticized in popular discourses, viewed as inferior to Americanized English, and conditioned out of the education system. The systematic characterization of AAVE and other Englishes as needing intervention limits the opportunities for celebrating individual difference and fostering a culturally sustaining classroom. A project like critical quilt making, that combines writing and the physical act of making something, manifests as an example of critical race theory in praxis, breaking the silence of a normalized discourse that has historically been used as a means of oppression against racial minorities in the U.S. (Ruiz & Sanchez, 2016, p. 13).
    </p><p>Quilts allow the use of exploration through the creation of social text, including representation of social experiences, resistance, and stories (Knowles & Cole, 2008). People of color continue to face a widespread problem of underrepresentation in higher education. Their attempts at self-expression may not be fully understood from the perspective of those who do not share a similar experience within the same racial or ethnic group, or by those who benefit from hierarchical social structures, and the power houses within, like the education system. According to the American Council of Education, over 40% of college and university students are people of color (POC), yet, less than 25% of the classroom teachers and administration are POC, leaving a dominant presence of white teachers and administrators who may lack the cultural competencies to embrace different cultures. White teachers and students who come from a more affluent background are typically surrounded by other white people, and are not exposed to the everyday underlying problems of POC. “Most White teachers have had little experience learning how to learn from someone else’s community, yet this is exactly what they will need to do in order to build pedagogy that is culturally and contextually relevant to students from backgrounds different from their own” (Sleeter, 2008, p. 563). The quilting project gave an opportunity for students to self-express their feelings, thoughts, and a composition story in a way they could personally connect with. Quilting gives a new meaning to what composition is, what writing is, and whose writing matters.
    </p>`);
    this.tileDescription.push(`<p>Quilting composition revises our ideas about what counts as writing, and part of building on this concept is figuring out what counts as critical making. For this project, quilting was the main subject of ‘media text’. Quilting was more than just sewing fabrics together, students created something that had an impactful meaning to them called “passionate attachments.” While recognizing their passionate attachments, students also read and reflected on short passages that focused on personal self-worth, beliefs, and discovering their own “truth”.
    </p><p>In the context of the classroom, “truth” was defined as what was right for each individual student, what made sense in their minds. Students expressed these feelings in their work through a combination of both quilting and writing. This combination takes place as a form of composition called “critical making” or “design thinking” (Newman, 2018). This form of composition goes deeper than words on paper. “Critical making is positioned at the intersection of the “scholarly” work of thinking and the material work of making; it serves as a catalyst for design, embedded in a process of craft, material, and exploration” (Schwartz, 2016), giving way to an open exchange of creativity and composition. Their focus is on making a bigger impact, embracing their differences, and creating a connection between what they write and what is their “truth”. Anson (2014) indicates that composition students are rarely permitted autonomous decision making about their writing. Conventionally, current traditional classrooms have assumed that students needed a set of rules for discourse to achieve polished, correct writing. Anneliese A. Singh (2010) who did a quilting project with her college students called the the Social Justice Quilt observes “the Social justice quilt supports a balance between two forces. One force looks back, so that students can “see” themselves in the history and her-story of liberation. The second force looks forward, so that they can see how they hold the products of liberation (e.g., opportunities, resources, access) in addition to holding the power to create change on behalf of others.” Like Singh points to, critical quilt making in the composition classroom anchors students in a particular history of what counts and who counts as composer, while empowering them to be agented decision makers about what they can accomplish through composing.
    </p>`);
    this.tileDescription.push(`<p>During class, after each major assignment, we would sit down and talk about the quilting experience and how quilting helped us out in our writing skills. These key conversations about transfer (Yancey, Robertson, and Taczak 2014) helped students visualize the writing process through concrete frames of reference. Here are some example observations we made about student experience:
    </p><p>●	Students noticed that just like in writing, they had to plan for the quilt block. They couldn’t just start sewing (or writing) without having a sense of direction. The tangible, physical processes of quilting helped students access and make metacognitive observations about the writing process.
    </p><p>●	There has to be a unifying thesis or theme. Every paper or essay needs a central thesis, just like the quilt blocks had a theme. Seeing how the diverse components of each block supported the main theme of the block helped students visualize how their claims mapped back to their central thesis.
    </p><p>●	In quilting there will be roadblocks. In writing there will also be roadblocks. The best thing to do is figure out the problem and find a solution. Quilting helped students engage in tangible problem solving which helped them gain access to theoretical problem solving skills.
    </p><p>●	Community quilting cultivated collaborative social skills as students talked to and learned from others in class. This helped students be more active and engaged in peer review of their written work. One group of quilters even read each other’s essays without the prompting of the instructor to gain more insight into the meaning of their quilt blocks so they could decide the best way to position them to sew together. Not only did this generate an authentic, informal peer review of the students’ writing, it also helped them make connections to how essays constellate together in larger networks and academic discourse communities.
    </p><p>●	Sometimes, papers and essays are composed in a group. The quilt taught cooperation and teamwork.
    </p>`);
    this.tileDescription.push(`<p>Giana’s story: Quilting was not something that I was expecting to do in an upper division writing class. As the concept was introduced, I couldn’t see how quilting could help my writing or even be a “true” representation of what a composition class was or should be. I was apprehensive about how executing the quilting project was going to, not only be relevant to writing, but if it was something that I was capable of producing. I, along with most of my classmates had never experienced quilting, or even knew what a quilt truly was, other than a “blanket”, a common answer from most of the students. We didn’t fully understand the context for which a quilt could hold, the deep emotional meanings that it could represent, or the history it could tell. In the end, quilting was used as imagery and text, allowing our identities as diverse individuals and as a group, giving us equal opportunity of recognition.
    </p><p>This particular GWAR class focused on the subject of cooperative argumentation. A class such as this, where the center focus was always on topics that were meant to push the students beyond a “comfort zone,” meant as a class, through our varying conflicting and agreeing opinions, we had to learn how to listen and understand the perspective of others. When writing did take place, it was composed of three short essays that focused on our experienced as we moved into different stages of completing the quilt. Since the writing was tied into our experiences, the writing portion was more challenging for others, as some students had a more difficult time choosing what their passionate attachment would be.
    </p><p>I thought creating my own block would be the hardest part, but the hardest part came when it was time for all the students to come together and put each of our quilt pieces together to start making one quilt. To make the transition from an individual project to a group one easier, we opted for reading the papers of some of our classmates to figure out the best way to put the quilt pieces in an arrangement that we all agreed worked best together. When looking at another students quilt block, many of the students had different perspectives on what that quilt block meant. But when we were able to read about that students inspiration behind their quilt block, it helped us get a better idea of their experience with the world. To physically see the quilt only gives a piece of the story, in order to get a deeper understanding and connection with the work, you must hear also know the story behind it.
    </p><p>The experience of mixing quilting and writing was an eye opener for a lot of students in the class, as we had discovered what seemed like an unconventional way of discussing diversity about ourselves and with each other. As we collectively sat together in class and talked about what each of our quilt pieces meant to us, it became more prominent that the importance of seeing our differences were even more important than seeing our similarities.
    </p>`);
    this.tileDescription.push(`<p>Alyssa’s story: Walking into the first day of my upper division writing class, I wasn’t really sure what to expect. I was in my second year of college and I was ready to be done with all my prerequisites. Being a Humanities and Communication major, I was used to writing essays and reading articles, so this class wasn’t worrying me too much. When Dr. Medina-López walked in, I could feel her scholarly yet fun energy, and I was already expecting to like this class. What I wasn’t expecting was to open up the syllabus and see the words “Cooperative Quilt Making.” With a shy, and somewhat sly smile on her face, Dr. Medina-López told the class that we would be quilting this semester alongside our readings and essays. You could hear the disbelief in the class. No one was expecting this, and almost no one actually wanted to put the time and energy into sewing.  Dr. Medina-López promised that it would be fun, and said that no one had to have any prior sewing experience because she also didn’t have any! Although a little caught off-guard, I decided to stick it out and stay enrolled in her class. From there, we were told that our individual blocks were going to be over our passionate attachments. Since I knew I’d never get this opportunity again, I knew I wanted to do mine on something fun.
    </p><p>Around the time of the class, I was really into marathon-watching television shows with my roommate, and it just so happen that Sex and the City was the show I was watching the most. After I decided on my passionate attachment, I had to figure out how I was going to design my block. Since each character has a distinct hairstyle, I knew it would be easy to just distinguish them by their hairdos. The four women live in New York City, and they love to be out at night, so I decided to make my block out of black fabric and sew on skyscrapers out of gray fabric. Lastly, to make sure everyone who looked at the block knew exactly what my block was about, I wrote the title of the show in pink fabric paint. With my plan drafted down on paper, I went out to buy a few supplies and started on my block.
    </p><p>Out of everything in that class, finishing my block was the easiest part. Yes, it was slightly hard to learn how to thread a needle and to actually sew, but it was all an individual process, so you didn’t have to worry about others not doing their part. Plus, I put a lot of time in my block, and I was really happy with how it turned out. The other steps of the project, however, included group work. After everyone was done with their blocks, we were assigned into groups of four to sew our blocks onto our groupmates’. Groupwork is interesting, especially when you have a groupmate sending multiple messages in the group-text you just created.
    </p><p>There was a total of six groups, and once those six groups were finished, we were supposed to get together with another group and sew our group of four blocks onto their groups blocks. All of that was going pretty smooth, until one student in class had to take the entire quilt home so he could sew his block onto it. That was all good and fine, as long as he kept the quilt safe and had it back in class by the next day. However, as that class period began, that student was nowhere to be found, and the rest of us didn’t know what to do; it was a quilting day, but how could we quilt if we didn’t have the quilt? After an hour, and multiple emails and phone calls, the student shows up to class with the quilt in hand. Major crisis averted.
    </p><p>The last step of the project was sewing the back onto the quilt. When it was time for that, we weren’t sure if we had a big enough piece of fabric to fit the back. One student suggested that we used a sheet, and even offered to run home really quick and go get it. Deciding that was the best option, she went and got it. Since we wanted everyone to have an equal amount of sewing work, we each had to sew a twelve-inch seam around the quilt to sew it onto the back. This part turned out to be extra difficult, because it’s hard getting flimsy needles to grow through so much fabric. However, once you and everyone else in class was done, all you had to do was sign the back and the quilt was complete.
    </p><p>After each step of the quilt, we would have to write essays on our experiences. After we submitted our essays, we would hold a class discussion and talk about what we wrote in our papers. It was fun and interesting to get to know the other students, and to see why they were attached to their passionate attachments. This was also where we would converse about how quilting would help with writing.
    </p><p>Overall, I loved Dr. Medina-López’s class. Quilting was a nice change from the boring tradition of only reading proper texts and writing essays. Not only did we get to do those things, but we were able to be creative in the process, which made our writings even better. To make matters even better, the quilt came out looking amazing, and I left that class feeling accomplished as a quilter and as a writer.
    </p>`);
    this.tileDescription.push(`<p>Kelly’s story: Our intention was to sew together a digital quilt that reflects our tangible quilt which is a metaphor for a theoretical quilting together of critical making in the composition classroom as decolonial feminist rasquache maker project. This project decolonizes composition classroom theory and praxis on multiple distinct and thought-provoking levels, in hopes that it might propel forward the decolonial futures of composition studies. First, it contributes to a contemporary scholarly conversation about the rhetorical value of indigenous textiles (Haas, Arellano) as decolonial social justice projects. Second, it merges that conversation with classroom pedagogy, providing practical classroom tools for accessing the community epistemologies of students of color and centering classroom activities around that knowledge.  Finally, and perhaps only to be made visible now, it gives a glimpse into what undergraduate mentoring with students and faculty of color in the humanities, particularly rhetoric and writing studies, can materialize as. The digital quilt is a collaborative mentoring project that developed over more than a year of sewing, discussing, writing, conference presentations and workshops, an all-expenses paid trip to Hawaii (!), eating pizza in my office, and sharing stories.
    Building on the intimate and nuanced understanding of what mentoring looks like in rhetoric and composition through story in Eble and Gaillet’s (2008) Stories of Mentoring, this story of mentoring is evidenced through its product, a student-driven research article. Thus, this article, our digital quilt, becomes an artifact, tool, and model for/how collaborative mentoring with first generation, underrepresented minority students and faculty of color can look. In their recent article on latinx mentoring in rhetoric and composition, “Advocating Comadrismo,” Ana Milena Ribero and Sonia Arellano (2019) argue, “mentoring of people of color in rhetoric and composition can be the sort of activist practice that works against the hegemony of whiteness in writing studies and in academia” (338). The digital quilt as rhetoric and composition mentoring praxis supports that call by disrupting traditional hierarchies of power and knowledge that predetermine who counts as author and expert in our field. It also builds an educational pathway to graduate school through earlier professionalization for first generation and students of color who would not have considered it an option prior to engaging in such work, further dismantling the hegemony of whiteness in academia. As scholars in rhetoric and composition and beyond continue to grapple with how to build a more equitable academy and the role of mentoring in supporting those goals, the digital quilt reminds us that sometimes one our greatest underused resources are the students themselves.
    Giana Hamilton, Leslie Maldonado Alyssa Riley, Erik Ring-Walters and myself were all hailed to this project for different reasons. I cannot speak for my fellow quilters, but I leave this project with a profound new understanding of the impact that decolonial maker projects as composition pedagogy and critical collaborative mentoring can have on supporting underrepresented minority and first generation undergraduate students. I look forward to more stories that not only tell, but also show similar projects in action.
  </p>`);
    this.tileDescription.push(`<p>We would like to thank California State University, Monterey Bay’s Undergraduate Resource Opportunities Center, Associated Students, School of Humanities and Communication, and College of Arts, Humanities, and Social Sciences for their support of this project.</p>`);
    this.tileDescription.push(`<p>Anson, C. M. (2014). Process pedagogy and its legacy. In G. Tate, A. R. Taggart, K. Schick, &
    </p><p>H. B. Hessler (Eds.), A Guide to Composition Pedagogies, New York: Oxford University Press. 212-230
    </p><p>Arellano, S. C. (2017). Quilting the Migrant Trail: Rhetorical Text(iles) and Rehumanizing
    </p><p>Narratives (Doctoral dissertation). Retrieved from Open Access Theses and Dissertations. http://hdl.handle.net/10150/625387
    </p><p>Astin, A. W., & Oseguera, L. (2004). The declining" equity" of American higher education. The
    </p><p>Review of Higher Education, 27(3), 321-341.
    </p><p>Ayers, E. L. (2001). The Pasts and Futures of Digital History. History News, 56(4), 5-9.
    </p><p>Retrieved from https://www.jstor.org/stable/42655551
    </p><p>Bartholomae, D. (1986). Inventing the university. Journal of Basic Writing, 5(1), 4-23.
    </p><p>Bazalgette, C., & Buckingham, D. (2012). Literacy, media, and multimodality: a critical
    </p><p>response.  Literacy, 47(2), 95-102. https://doi.org/10.1111/j.1741-4369.2012.00666.x
    </p><p>Bird, B. (2010). Meaning-Making Concepts: Basic Writer’s Access to Verbal Culture.
    </p><p>Conference on Basic Writing, 1-18. Retrieved from https://bwe.ccny.cuny.edu/Meaning
    </p><p>Making%20%Concept%20%20Basic%20Writer’s%20Access%20to%20Verbal%20Cul
    </p><p>ure.pdf
    </p><p>Blair, C., & Michel, N. (2007). The AIDS Memorial Quilt and the contemporary culture of
    </p><p>public commemoration. Rhetoric and Public Affairs, 595-626.
    </p><p>Bolick, C. M. (2006). Digital Archives: Democratizing the Doing of History. International
    </p><p>Journal of Social Education, 21(1), 122-134. Retrieved from http://eric.ed.gov/PDFS/EJ782136.pdf
    </p><p>Butler, J. (1997). The Psychic Life of Power. Stanford: Stanford University Press.
    </p><p>Cushman, E. (2013). Wampum, Sequoyan, and Story: Decolonizing the Digital Archive. College
    </p><p>English, 76(2), 115-135. Retrieved from http://www.jstor.org/stable/24238145
    </p><p>Duncum, P. (2004). Visual Culture Isn’t Just Visual: Multiliteracy, Multimodality and Meaning.
    </p><p>Studies in Art Education, 45(3), 252-264. Retrieved from https://www.jstor.org/stable/
    </p><p>1320972
    </p><p>Diaz, G., & McKenna, M. B. (2017). Using the Creative Process as Pedagogy. Preparing
    </p><p>Educators for Arts Integration: Placing Creativity at the Center of Learning, 19.
    </p><p>Eble, M. F., & Gaillet, L. L. (Eds.). (2008). Stories of mentoring: Theory and praxis. Parlor
    </p><p>Press.
    </p><p>Enoch, J. (2010). Changing Research Methods, Changing History: A Reflection on Language,
    </p><p>Location, and Archive. Compassion Studies, 38(2), 47-73. Retrieved from https://
    </p><p>www.jstor.org/stable/compstud.38.2.0047
    </p><p>Farkas, D. K., & Farkas, J. B. (2002). Principles of Web Design. New York City, NY: Longman
    </p><p>Frost, E. (2015). Apparent Feminism as a Methodology for Technical Communication and
    </p><p>Rhetoric. Journal of Business and Technical Communication, 30(1), 3-28. doi: 10.1177/1050651915602295
    </p><p>García-Galera, M. C., & Valdivia, A. (2014). Media prosumers. Participatory culture of
    </p><p>audiences and media responsibility. Comunicar, 22(43), 10-13.
    </p><p>Haas, A. M. (2012). Race, rhetoric, and technology: A case study of
    </p><p>decolonial technical communication theory, methodology, and pedagogy. Journal of Business and Technical Communication, 26(3), 277-310.
    </p><p>Haas, A.M. (2007). Wampum as hypertext: An American Indian intellectual tradition of
    </p><p>multimedia theory and practice. Studies in American Indian Literatures, 19(4), 77-100.
    </p><p>hooks, b. (1990). Postmodern Blackness. Postmodern Culture 1(1), Johns Hopkins University
    </p><p>Press. Retrieved June 25, 2019, from Project MUSE database
    </p><p>Kress, G. (2012). Recognizing learning: a perspective from a social semiotic theory	multimodality. Multilingualism and Multimodality: Currently challenges for Educational
    </p><p>Studies, 119-132. Retrieved from https://ebookcentral.proquest.com/lib/csumb/detail
    </p><p>.action?docID=3034865
    </p><p>Leon, K. (2013) La Hermandad and Chicanas Organizing: The Community Rhetoric of the
    </p><p>Comisión Femenil Mexicana Nacional Organización. Community Literacy Journal, 7(3).
    </p><p>Retrieved from http://www.communityliteracy.org/index.php/clj/article/view/167
    </p><p>Liu, J. (2013). Visual Images Interpretive Strategies in Multimodal Texts. Journal of Language
    </p><p>Teaching and Research, 4(6), 1259-1263. doi: 10.4304
    </p><p>MacDowell, M., Donaldson, B., Worrall, M., & Swanson, L. (2016). Quilts and Human Rights.
    </p><p>University of Nebraska Press.
    </p><p>Makau, J. M., & Marty, D. L. (2001). Cooperative argumentation: A model for deliberative
    </p><p>community. Waveland Press.
    </p><p>Martinez, A. Y. (2014). A plea for critical race theory counterstory: Stock story versus
    </p><p>counterstory dialogues concerning Alejandra's" fit" in the academy. Composition Studies, 33-55.
    </p><p>Mesa-Bains, A. (2003). Domesticana: The sensibility of Chicana rasquachismo. Chicana
    </p><p>Feminisms: A critical reader, 298-315.
    </p><p>Mora, A. R. (2014). Counter-narrative. Key Concepts in Intercultural Dialogue, 36, 23-44.
    </p><p>Retrieved from https://s3.amazonaws.com/academia.edu.documents/38363542/key-concept-counter-narrative.pdf
    </p><p>National Council of Teachers of English. (2005). Position Statement on Multimodal Literacies.
    </p><p>Retrieved from http://www2.ncte.org/statement/multimodalliteracies/
    </p><p>Newman, J. N. (2018). Designing the teacher: Applying 'design thinking' to improve composition
    </p><p>pedagogy and practice. ProQuest dissertations & theses global: The humanities and
    </p><p>social sciences collection. Eastern Kentucky University. 2-3
    </p><p>Odland, J. C. (2006). Fashioning Tradition: Maya Huipiles in the Field Museum
    </p><p>Collections. Fieldiana. Anthropology, i-67.
    </p><p>Powell, M. (2014). Contemporary Theories of Rhetoric course syllabus. Michigan State
    </p><p>University, East Lansing, Michigan.
    </p><p>Ratto, M. Megan Boler, eds.(2014) DIY Citizenship: Critical Making and Social Media.
    </p><p>Ratto, M., & Ree, R. (2012). Materializing information: 3D printing and social change. First
    </p><p>Monday, 17(7).
    </p><p>Ribero A.M. & Arellano, S.C. (2019). Advocating Comadrismo: A Feminist Mentoring
    </p><p>Approach for Latinas in Rhetoric and Composition, 21(2), 334-256.
    </p><p>Rose, M. (2009). Why school?: Reclaiming education for all of us. The New Press.
    </p><p>Ruiz, I. D., & Sánchez, R. (Eds.). (2016). Decolonizing rhetoric and composition studies: New
    </p><p>Latinx keywords for theory and pedagogy. Springer.
    </p><p>Sano-Franchini, J. (2019). Teaching. Retrieved from http://www.jsanofranchini.com/teaching/
    </p><p>
    </p><p>Schwartz, C. (2016). Critical making: Exploring the use of making as a generative tool.  Journal
    </p><p>of Curriculum and Pedagogy, 13(3), 227-248. https://doi.org/10.1080/15505170.2016.
    </p><p>1200168
    </p><p>Shaughnessy, M. P. (1976). Diving in: An introduction to basic writing. College Composition
    </p><p>and Communication, 27(3), 234-239.
    </p><p>Sheridan, D. M., Ridolfo, J., & Michel, A. J. (2012). The available means of persuasion:
    </p><p>Mapping a theory and pedagogy of multimodal public rhetoric. Anderson, SC: Parlor Press.
    </p><p>Shipka, J. (2011). Toward a composition made whole. University of Pittsburgh Pre.
    </p><p>Singh, A. A. (2010). Teaching Social Justice Advocacy: Using the Metaphor of a Quilt.
    </p><p>Psychology of Women Quarterly, 34(4), 550–553. https://doi.org/10.1111/j.1471-6402.2010.01604.x
    </p><p>Sleeter, C. (2008). 32 Preparing White teachers for diverse students. Retrieved from
    </p><p>https://s3.amazonaws.com/academia.edu.documents/38675437/2008_Preparing_white_teachers.pdf?response-content
    </p><p>disposition=inline%3B%20filename%3DPreparing_White_teachers_for_diverse_stu.pdf
    </p><p>Social Justice Sewing Academy. (2019). Home. Retrieved from http://www.sjsacademy.com/.
    </p><p>Tobin, J. L., & Dobard, R.G. (2000). Hidden in plain view: The secret story of quilts and the
    </p><p>Underground Railroad. Anchor.
    </p><p>Yancey, K., Robertson, L., & Taczak, K. (2014). Writing across contexts: Transfer, composition,	and sites of writing. University Press of Colorado.
    </p><p>Ybarra-Frausto, T. (1989). Rasquachismo: a Chicano sensibility. School by the River Press.
    </p>`);

    this.tileDescription.push(`
    <h4>Figure 1. Students planning and beginning their quilt blocks using donated fabrics (2018).
    </h4>
    <img src='../assets/img/gallery/Figure1.jpg' width='600px' alt='Figure1' transform:'rotate(45deg)'/>

    <h4>Figure 2. After the students finished their blocks, they deliberated on how to best arrange the blocks into the quilt. The original plan was to include three additional co-constructed class blocks, but that plan had to be revised after a student left the class (2018).
    </h4>
    <img src='../assets/img/gallery/Figure2.jpg' width='600px' alt='Figure2'/>

    <h4>Figure 3. Students took turns sewing the binding of the quilt. Each student was responsible for sewing one section of the binding (2018).
    </h4>
    <img src='../assets/img/gallery/Figure3.jpg' width='600px' alt='Figure3'/>

    <h4>Figure 4. The class and the quilt on the last day of class during a “Quilt Party” celebrating our accomplishments (2018).
    </h4>
    <img src='../assets/img/gallery/Figure4.jpg' width='600px' alt='Figure4'/>

    <h4>Figure 5. Kelly Medina-López, Alyssa Riley, Leslie Maldonado, and Giana Hamilton presenting their “Quilting Composition” research at the 2018 CSUMB Summer Research Symposium.
    </h4>
    <img src='../assets/img/gallery/Figure5.jpg' width='600px' alt='Figure5'/>
    `)

    this.tileDescription.push(`
    <h4>Figure 6. Alyssa Riley, Giana Hamilton, and Leslie Maldonado presenting their research during a poster session at the 2018 CSUMB Summer Research Symposium.
    </h4>
    <img src='../assets/img/gallery/Figure6.jpg' height='450px' alt='Figure6'/>

    <h4>Figure 7. Preparing quilt blocks for a workshop at the 2019 Conference on College Composition and Communication in Kelly’s office.
    </h4>
    <img src='../assets/img/gallery/Figure7.jpg' height='500px' alt='Figure7'/>

    <h4>Figure 8. Leslie Maldonado, Giana Hamilton, Kelly Medina-López, and Alyssa Riley hosting a workshop at the 2019 Conference on College Composition and Communication.
    </h4>
    <img src='../assets/img/gallery/Figure8.jpg' width='600px' alt='Figure8'/>

    <h4>Figure 9. Quilting with workshop participants at the 2019 Conference on College Composition and Communication.
    </h4>
    <img src='../assets/img/gallery/Figure9.jpg' width='600px' alt='Figure9'/>

    <h4>Figure 10. Workshop participants at the 2019 Conference on College Composition and Communication sewed a quilt of “scholarly identities.”
    </h4>
    <img src='../assets/img/gallery/Figure10.jpg' width='600px' alt='Figure10'/>`)

    this.tileDescription.push(`
    `)


    //titles
    this.tileTitle.push(` `); // [0] is empty
    this.tileTitle.push(`1.	Get Ready`);
    this.tileTitle.push(`2. The Quilters`);
    this.tileTitle.push(`3. Plan the Pattern`);
    this.tileTitle.push(`4. Gather Tools`);
    this.tileTitle.push(`5. Needles & Thread`);
    this.tileTitle.push(`6. Fabric`);
    this.tileTitle.push(`7. Scissors`);
    this.tileTitle.push(`8. Pins`);
    this.tileTitle.push(`9. Ruler`);
    this.tileTitle.push(`10. Measure`);
    this.tileTitle.push(`11. Measure Again`);
    this.tileTitle.push(`12. Cut`);
    this.tileTitle.push(`13. Patchwork`);
    this.tileTitle.push(`14. Baste`);
    this.tileTitle.push(`15. Stitch`);
    this.tileTitle.push(`16. Bind`);
    this.tileTitle.push(`17. Admire`);
    this.tileTitle.push(`18. Reflect`);
    this.tileTitle.push(`19. Get Cozy!`);
    this.tileTitle.push(`20. Acknowledgements`);
    this.tileTitle.push(`21. Work Cited`);
    this.tileTitle.push(`22. Gallery Pt. 1`);
    this.tileTitle.push(`23. Gallery Pt. 2`);
    this.tileTitle.push(`24. About the Quilters`);

    for(let i = 1; i <= 24; i++) {
      this.setDetails(i, this.tileTitle[i], this.tileDescription[i]);
    }
  }

   setDetails(id: number, title: string, details: string) {
    this.tiles.Item(String(id)).title = title;
    this.tiles.Item(String(id)).details = details;
   }

   getTile(id: number) {
    return this.tiles.Item(String(id));
   }

   getTileID(id: number) {
    return this.tiles;
   }



}
